site_name: URL Shortener Documentation
site_description: Comprehensive documentation for the URL Shortener project
site_author: Osman Makhtoom
site_url: https://osmanmakhtoom.github.io/url-shortener

repo_name: osmanmakhtoom/url-shortener
repo_url: https://github.com/osmanmakhtoom/url-shortener
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

nav:
  - Home: README.md
  - User Guide:
    - Overview: user/README.md
    - Getting Started: user/getting-started.md
    - User Guide: user/user-guide.md
  - Developer:
    - Development Setup: developer/development-setup.md
    - Development Toolbox: developer/TASKFILE.md
    - Contributing: developer/contributing.md
  - API:
    - API Reference: api/API.md
  - Deployment:
    - Deployment Guide: deployment/DEPLOYMENT.md
  - Testing:
    - Testing Guide: testing/TESTING.md
  - Architecture:
    - Scalability: architecture/SCALABILITY.md
    - Service Design: architecture/SERVICE_ORIENTED_DESIGN.md
  - Project:
    - Changelog: CHANGELOG.md
    - Documentation Summary: DOCUMENTATION_SUMMARY.md

plugins:
  - search
  - mkdocs-material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/osmanmakhtoom/url-shortener
    - icon: fontawesome/brands/telegram
      link: https://t.me/osman_makhtoom
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/osman-makhtoom
    - icon: fontawesome/solid/envelope
      link: mailto:osmanmakhtoom@gmail.com
  version:
    provider: mike
